import pathlib as p

def process_file(file: p.Path, includes:list[str]) -> str:
    processed = ""
    with file.open("r", encoding="utf-8") as f:
        for line in f.readlines():
            match line:
                case line if line == "#pragma once\n":
                    pass

                case line if line.startswith("#include \""):
                    pass

                case line if line.startswith("#include <"):
                    if line not in includes:
                        includes.append(line)

                case _:
                    processed += line
                    pass

    return processed

def get_internal_includes(file:p.Path, files):
    lines = []

    with file.open("r", encoding="utf-8") as f:
        filtered = filter(lambda l: "#include \"" in l, f.readlines())
        lines = [l.rstrip().replace("#include","").replace("\"","").replace(" ","") for l in filtered]

    return [f for f in files if f.name in lines]
   
def order_includes(include_map: dict[p.Path, list[p.Path]]) -> list[p.Path]:
    added_headers = []
    visited = set()
    visiting = set()  
    
    def visit(file):
        if file in visited:
            return
        if file in visiting:
            raise ValueError(f"Circular dependency detected involving {file}")
        
        visiting.add(file)
        
        for dep in include_map.get(file, []):
            if dep in include_map:  
                visit(dep)
        
        visiting.remove(file)
        visited.add(file)
        added_headers.append(file)
    
    for file in include_map:
        visit(file)
    
    return added_headers    

def main():
    files:list[p.Path] = list(p.Path("headers").glob("*.h")) 
    include_map = {f:get_internal_includes(f,files) for f in files}
    ordered_files = order_includes(include_map) + list(p.Path("src").glob("*.hpp"))
    includes = []
    processed_files = [process_file(file, includes) for file in ordered_files]

    with open("cardozo.h", "w", encoding="utf-8") as f:
        f.write("/*\nCardozo.h\nThis header file was autogenerated by the build system.\n----------\n*/\n\n")
        f.write("#pragma once \n")
        f.writelines("".join(includes + processed_files))

if __name__ == '__main__':
    main()
